projects:
  aiot-test-AppSync-App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: uzx5pftlzjgrdc6s4yokcvaiiy
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-2
extensions:
  amplify:
    version: 3
