// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_content_delivery_bucket": "aiotest-20180927202952--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d3n2wrf9ttsajg.cloudfront.net",
    "aws_cognito_identity_pool_id": "ap-southeast-2:1f49afa4-69da-4ce9-8242-b8695e70ce41",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_vmQaQnfVx",
    "aws_user_pools_web_client_id": "3mrdm4tqs0b6amu8kleilsptfi",
    "aws_cloud_logic_custom": [
        {
            "name": "thingApi",
            "endpoint": "https://ycexvq2fxg.execute-api.ap-southeast-2.amazonaws.com/Prod",
            "region": "ap-southeast-2"
        },
        {
            "name": "thingAllow",
            "endpoint": "https://zew97lxc3d.execute-api.ap-southeast-2.amazonaws.com/Prod",
            "region": "ap-southeast-2"
        },
        {
            "name": "solutionApi",
            "endpoint": "https://8zp9pz3ni4.execute-api.ap-southeast-2.amazonaws.com/Prod",
            "region": "ap-southeast-2"
        }
    ]
};


export default awsmobile;
