// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_IulUEVNt3",
    "aws_user_pools_web_client_id": "2vrsh2qhr92dbe1pkk7j7kbpb3"
};


export default awsmobile;
